/** @type {import('tailwindcss').Config} */
const colorTokens = require("./src/shared/design-system/colors.json");

module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  safelist: [
    "bg-background",
    "bg-surface",
    "bg-surface-subtle",
    "text-text-primary",
    "text-text-secondary",
    "bg-primary",
    "bg-primary-strong",
    "bg-secondary",
    "bg-accent",
    "bg-brand-soft",
    "bg-warm-soft",
    "border-border",
    "border-border-strong",
    "text-error",
    "text-success",
    "text-warning",
    "text-on-primary",
    "text-on-secondary",
    "text-on-accent",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        background: colorTokens.background,
        surface: colorTokens.surface,
        "surface-subtle": colorTokens.surfaceSubtle,
        "text-primary": colorTokens.textPrimary,
        "text-secondary": colorTokens.textSecondary,
        primary: colorTokens.primary,
        "primary-strong": colorTokens.primaryStrong,
        secondary: colorTokens.secondary,
        "brand-soft": colorTokens.brandSoft,
        accent: colorTokens.accent,
        "warm-soft": colorTokens.warmSoft,
        border: colorTokens.border,
        "border-strong": colorTokens.borderStrong,
        error: colorTokens.error,
        success: colorTokens.success,
        warning: colorTokens.warning,
        "on-primary": colorTokens.onPrimary,
        "on-secondary": colorTokens.onSecondary,
        "on-accent": colorTokens.onAccent,
      },
    },
  },
  plugins: [],
};
