[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tara", email = "nandayavanets@mail.ru" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "recipe-scrapers>=15.12.0",
    "supabase>=2.31.0",
    "urllib3>=2.7.0",
]

[project.scripts]
server = "server.main:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
