SET local check_function_bodies = off;

CREATE SCHEMA "private";

CREATE TABLE "public"."cookbook_recipes" (
  "cookbook_id" uuid NOT NULL,
  "recipe_id"   uuid NOT NULL,
  CONSTRAINT "cookbook_recipes_pkey" PRIMARY KEY (cookbook_id, recipe_id)
);

ALTER TABLE "public"."cookbook_recipes"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."cookbooks" (
  "id"            uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "owner_user_id" uuid                     NOT NULL,
  "title"         text                     NOT NULL,
  "created_at"    timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "cookbooks_pkey" PRIMARY KEY (id),
  CONSTRAINT "cookbooks_title_check" CHECK (((title = btrim(title)) AND ((char_length(title) >= 1) AND (char_length(title) <= 100))))
);

ALTER TABLE "public"."cookbooks"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."household_join_codes" (
  "household_id" uuid                     NOT NULL,
  "code_digest"  text                     NOT NULL,
  "created_by"   uuid                     NOT NULL,
  "created_at"   timestamp with time zone NOT NULL DEFAULT now(),
  "expires_at"   timestamp with time zone NOT NULL,
  CONSTRAINT "household_join_codes_code_key" UNIQUE (code_digest),
  CONSTRAINT "household_join_codes_digest_format" CHECK ((code_digest ~ '^[0-9a-f]{64}$'::text)),
  CONSTRAINT "household_join_codes_pkey" PRIMARY KEY (household_id)
);

ALTER TABLE "public"."household_join_codes"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."household_join_rate_limits" (
  "user_id"           uuid                     NOT NULL,
  "window_started_at" timestamp with time zone NOT NULL DEFAULT now(),
  "failed_attempts"   integer                  NOT NULL DEFAULT 0,
  "locked_until"      timestamp with time zone,
  CONSTRAINT "household_join_rate_limits_failed_attempts_check" CHECK ((failed_attempts >= 0)),
  CONSTRAINT "household_join_rate_limits_pkey" PRIMARY KEY (user_id)
);

ALTER TABLE "public"."household_join_rate_limits"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."household_members" (
  "id"                    uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "household_id"          uuid                     NOT NULL,
  "user_id"               uuid                     NOT NULL,
  "role"                  text                     NOT NULL,
  "joined_at"             timestamp with time zone NOT NULL DEFAULT now(),
  "last_seen_activity_id" bigint,
  CONSTRAINT "household_members_household_id_user_id_key" UNIQUE (household_id, user_id),
  CONSTRAINT "household_members_pkey" PRIMARY KEY (id),
  CONSTRAINT "household_members_role_check" CHECK ((role = ANY (ARRAY['owner'::text, 'member'::text])))
);

ALTER TABLE "public"."household_members"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."household_recipe_activities" (
  "id"                 bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "household_id"       uuid                     NOT NULL,
  "actor_user_id"      uuid,
  "actor_display_name" text                     NOT NULL,
  "action"             text                     NOT NULL,
  "recipe_id"          uuid,
  "recipe_title"       text                     NOT NULL,
  "created_at"         timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "household_recipe_activities_action_check" CHECK ((action = ANY (ARRAY['added'::text, 'edited'::text, 'unshared'::text]))),
  CONSTRAINT "household_recipe_activities_actor_display_name_check" CHECK ((NULLIF(btrim(actor_display_name), ''::text) IS NOT NULL)),
  CONSTRAINT "household_recipe_activities_pkey" PRIMARY KEY (id),
  CONSTRAINT "household_recipe_activities_recipe_title_check" CHECK ((NULLIF(btrim(recipe_title), ''::text) IS NOT NULL))
);

ALTER TABLE "public"."household_recipe_activities"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."household_recipe_shares" (
  "household_id" uuid                     NOT NULL,
  "recipe_id"    uuid                     NOT NULL,
  "shared_at"    timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "household_recipe_shares_pkey" PRIMARY KEY (household_id, recipe_id)
);

ALTER TABLE "public"."household_recipe_shares"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."households" (
  "id"         uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "name"       text                     NOT NULL,
  "created_by" uuid,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "households_name_check" CHECK (((char_length(TRIM(BOTH FROM name)) >= 1) AND (char_length(TRIM(BOTH FROM name)) <= 100))),
  CONSTRAINT "households_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."households"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."profiles" (
  "id"                      uuid                     NOT NULL,
  "display_name"            text,
  "avatar_url"              text,
  "onboarding_completed_at" timestamp with time zone,
  "created_at"              timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"              timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "profiles_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."profiles"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."recipes" (
  "id"                    uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "owner_user_id"         uuid                     NOT NULL,
  "title"                 text                     NOT NULL,
  "description"           text,
  "image_url"             text,
  "ingredients"           jsonb                    NOT NULL DEFAULT '[]'::jsonb,
  "instructions"          jsonb                    NOT NULL DEFAULT '[]'::jsonb,
  "source_type"           text                     NOT NULL DEFAULT 'my_recipe'::text,
  "source_url"            text,
  "created_at"            timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"            timestamp with time zone NOT NULL DEFAULT now(),
  "servings"              integer                  NOT NULL DEFAULT 1,
  "nutrition_per_serving" jsonb,
  "prep_time_minutes"     integer,
  "cook_time_minutes"     integer,
  "source_person_name"    text,
  "image_path"            text,
  CONSTRAINT "recipes_cook_time_minutes_check" CHECK (((cook_time_minutes IS NULL) OR (cook_time_minutes >= 0))),
  CONSTRAINT "recipes_ingredients_array_check" CHECK ((jsonb_typeof(ingredients) = 'array'::text)),
  CONSTRAINT "recipes_instructions_array_check" CHECK ((jsonb_typeof(instructions) = 'array'::text)),
  CONSTRAINT "recipes_nutrition_per_serving_check" CHECK (((nutrition_per_serving IS NULL) OR (jsonb_typeof(nutrition_per_serving) = 'object'::text))),
  CONSTRAINT "recipes_pkey" PRIMARY KEY (id),
  CONSTRAINT "recipes_prep_time_minutes_check" CHECK (((prep_time_minutes IS NULL) OR (prep_time_minutes >= 0))),
  CONSTRAINT "recipes_servings_check" CHECK (((servings IS NULL) OR (servings > 0))),
  CONSTRAINT "recipes_source_details_check"
    CHECK
    ((((source_type = 'my_recipe'::text) AND (source_person_name IS NULL) AND (source_url IS NULL)) OR ((source_type = 'family'::text) AND (NULLIF(TRIM(BOTH FROM
    source_person_name),
    ''::text) IS NOT NULL) AND (source_url IS NULL)) OR ((source_type = 'website'::text) AND (source_person_name IS NULL) AND (NULLIF(TRIM(BOTH FROM source_url), ''::text) IS
    NOT NULL)))),
  CONSTRAINT "recipes_source_type_check" CHECK ((source_type = ANY (ARRAY['my_recipe'::text, 'family'::text, 'website'::text]))),
  CONSTRAINT "recipes_title_check" CHECK (((char_length(TRIM(BOTH FROM title)) >= 1) AND (char_length(TRIM(BOTH FROM title)) <= 200)))
);

ALTER TABLE "public"."recipes"
  ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION private.household_join_rate_limit (
  p_user_id   uuid,
  p_succeeded boolean DEFAULT NULL::boolean
)
  RETURNS timestamp WITH time zone
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
declare
  v_now timestamptz := now();
  v_failed_attempts integer;
  v_window_started_at timestamptz;
  v_locked_until timestamptz;
begin
  insert into public.household_join_rate_limits (user_id)
  values (p_user_id)
  on conflict (user_id) do nothing;

  select failed_attempts, window_started_at, locked_until
  into v_failed_attempts, v_window_started_at, v_locked_until
  from public.household_join_rate_limits
  where user_id = p_user_id
  for update;

  if p_succeeded is null then
    if (v_locked_until is not null and v_locked_until <= v_now)
      or v_window_started_at <= v_now - interval '10 minutes'
    then
      update public.household_join_rate_limits
      set failed_attempts = 0,
          window_started_at = v_now,
          locked_until = null
      where user_id = p_user_id;
      return null;
    end if;

    if v_locked_until > v_now then
      return v_locked_until;
    end if;

    return null;
  end if;

  if p_succeeded then
    update public.household_join_rate_limits
    set failed_attempts = 0,
        window_started_at = v_now,
        locked_until = null
    where user_id = p_user_id;
    return null;
  end if;

  update public.household_join_rate_limits
  set failed_attempts = failed_attempts + 1,
      locked_until = case
        when failed_attempts + 1 >= 10 then v_now + interval '10 minutes'
        else null
      end
  where user_id = p_user_id
  returning locked_until into v_locked_until;

  return v_locked_until;
end;
$function$;

CREATE OR REPLACE FUNCTION private.record_household_recipe_activity (
  p_household_id uuid,
  p_recipe_id    uuid,
  p_recipe_title text,
  p_action       text
)
  RETURNS void
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
declare
  v_user_id uuid := auth.uid();
  v_actor_display_name text;
begin
  if v_user_id is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;

  if p_action not in ('added', 'edited', 'unshared') then
    raise exception 'invalid household recipe activity' using errcode = '22023';
  end if;

  if not exists (
    select 1
    from public.recipes recipes
    where recipes.id = p_recipe_id
      and recipes.owner_user_id = v_user_id
  ) then
    raise exception 'recipe ownership required' using errcode = '42501';
  end if;

  select coalesce(
    nullif(btrim(to_jsonb(profiles) ->> 'display_name'), ''),
    nullif(btrim(to_jsonb(profiles) ->> 'full_name'), ''),
    nullif(btrim(to_jsonb(profiles) ->> 'name'), ''),
    nullif(btrim(users.raw_user_meta_data ->> 'full_name'), ''),
    nullif(btrim(users.raw_user_meta_data ->> 'name'), ''),
    case
      when members.role = 'owner' then 'Household owner'
      else 'Household member'
    end
  )
  into v_actor_display_name
  from public.household_members members
  left join public.profiles profiles on profiles.id = members.user_id
  left join auth.users users on users.id = members.user_id
  where members.household_id = p_household_id
    and members.user_id = v_user_id;

  if not found then
    raise exception 'household membership required' using errcode = '42501';
  end if;

  insert into public.household_recipe_activities (
    household_id,
    actor_user_id,
    actor_display_name,
    action,
    recipe_id,
    recipe_title
  ) values (
    p_household_id,
    v_user_id,
    v_actor_display_name,
    p_action,
    p_recipe_id,
    coalesce(nullif(btrim(p_recipe_title), ''), 'Untitled recipe')
  );
end;
$function$;

CREATE OR REPLACE FUNCTION private.record_shared_recipe_edit()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
declare
  v_household_id uuid;
begin
  for v_household_id in
    select shares.household_id
    from public.household_recipe_shares shares
    where shares.recipe_id = new.id
  loop
    perform private.record_household_recipe_activity(
      v_household_id,
      new.id,
      new.title,
      'edited'
    );
  end loop;

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.create_personal_cookbook (
  p_title      text,
  p_recipe_ids uuid[] DEFAULT '{}'::uuid[]
)
  RETURNS jsonb
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
declare
  v_user_id uuid := auth.uid();
  v_cookbook_id uuid;
begin
  if v_user_id is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;

  if p_title is null or char_length(btrim(p_title)) not between 1 and 100 then
    raise exception 'invalid cookbook title' using errcode = '22023';
  end if;

  if exists (
    select 1
    from unnest(coalesce(p_recipe_ids, '{}'::uuid[])) selected(recipe_id)
    where selected.recipe_id is null
      or not exists (
        select 1
        from public.recipes recipes
        where recipes.id = selected.recipe_id
          and recipes.owner_user_id = v_user_id
      )
  ) then
    return jsonb_build_object('status', 'INVALID_RECIPE');
  end if;

  insert into public.cookbooks (owner_user_id, title)
  values (v_user_id, btrim(p_title))
  returning id into v_cookbook_id;

  insert into public.cookbook_recipes (cookbook_id, recipe_id)
  select v_cookbook_id, selected.recipe_id
  from (
    select distinct recipe_id
    from unnest(coalesce(p_recipe_ids, '{}'::uuid[])) recipe_ids(recipe_id)
  ) selected;

  return jsonb_build_object(
    'status', 'OK',
    'cookbook_id', v_cookbook_id
  );
end;
$function$;

CREATE OR REPLACE FUNCTION public.get_household_activity()
  RETURNS jsonb
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
declare
  v_user_id uuid := auth.uid();
  v_household_id uuid;
  v_joined_at timestamptz;
  v_last_seen_activity_id bigint;
  v_member_count integer;
  v_latest_activity_id bigint;
  v_unread_count integer;
  v_activities jsonb;
begin
  if v_user_id is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;

  select members.household_id, members.joined_at, members.last_seen_activity_id
  into v_household_id, v_joined_at, v_last_seen_activity_id
  from public.household_members members
  where members.user_id = v_user_id;

  if not found then
    return jsonb_build_object('status', 'NO_HOUSEHOLD');
  end if;

  select count(*)::integer
  into v_member_count
  from public.household_members members
  where members.household_id = v_household_id;

  select max(activities.id)
  into v_latest_activity_id
  from public.household_recipe_activities activities
  where activities.household_id = v_household_id
    and activities.created_at >= v_joined_at;

  select count(*)::integer
  into v_unread_count
  from public.household_recipe_activities activities
  where activities.household_id = v_household_id
    and activities.created_at >= v_joined_at
    and activities.id > coalesce(v_last_seen_activity_id, 0)
    and activities.actor_user_id is distinct from v_user_id;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', visible.id,
        'actor_user_id', visible.actor_user_id,
        'actor_display_name', visible.actor_display_name,
        'action', visible.action,
        'recipe_id', visible.readable_recipe_id,
        'recipe_title', visible.recipe_title,
        'created_at', visible.created_at
      )
      order by visible.id desc
    ),
    '[]'::jsonb
  )
  into v_activities
  from (
    select
      activities.id,
      activities.actor_user_id,
      activities.actor_display_name,
      activities.action,
      case
        when activities.action <> 'unshared' and shares.recipe_id is not null
          then activities.recipe_id
        else null
      end as readable_recipe_id,
      activities.recipe_title,
      activities.created_at
    from public.household_recipe_activities activities
    left join public.household_recipe_shares shares
      on shares.household_id = activities.household_id
      and shares.recipe_id = activities.recipe_id
    where activities.household_id = v_household_id
      and activities.created_at >= v_joined_at
    order by activities.id desc
    limit 50
  ) visible;

  return jsonb_build_object(
    'status', 'OK',
    'member_count', v_member_count,
    'unread_count', v_unread_count,
    'latest_activity_id', v_latest_activity_id,
    'activities', v_activities
  );
end;
$function$;

CREATE OR REPLACE FUNCTION public.get_household_settings()
  RETURNS jsonb
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
declare
  v_user_id uuid := auth.uid();
  v_household_id uuid;
  v_household_name text;
  v_role text;
  v_members jsonb;
  v_code_expires_at timestamptz;
begin
  if v_user_id is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;

  select hm.household_id, h.name, hm.role
  into v_household_id, v_household_name, v_role
  from public.household_members hm
  join public.households h on h.id = hm.household_id
  where hm.user_id = v_user_id;

  if not found then
    return jsonb_build_object('status', 'NO_HOUSEHOLD');
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'user_id', members.user_id,
        'display_name', coalesce(
          nullif(btrim(to_jsonb(profiles) ->> 'display_name'), ''),
          nullif(btrim(to_jsonb(profiles) ->> 'full_name'), ''),
          nullif(btrim(to_jsonb(profiles) ->> 'name'), ''),
          nullif(btrim(users.raw_user_meta_data ->> 'full_name'), ''),
          nullif(btrim(users.raw_user_meta_data ->> 'name'), ''),
          case
            when members.role = 'owner' then 'Household owner'
            else 'Household member'
          end
        ),
        'role', members.role
      )
      order by (members.role = 'owner') desc, members.joined_at, members.user_id
    ),
    '[]'::jsonb
  )
  into v_members
  from public.household_members members
  left join public.profiles profiles on profiles.id = members.user_id
  left join auth.users users on users.id = members.user_id
  where members.household_id = v_household_id;

  if v_role = 'owner' then
    select expires_at
    into v_code_expires_at
    from public.household_join_codes
    where household_id = v_household_id
      and expires_at > now();
  end if;

  return jsonb_build_object(
    'status', 'OK',
    'household_id', v_household_id,
    'household_name', v_household_name,
    'role', v_role,
    'member_count', jsonb_array_length(v_members),
    'members', v_members,
    'active_code_expires_at', v_code_expires_at
  );
end;
$function$;

CREATE OR REPLACE FUNCTION public.handle_new_user()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
begin
  insert into public.profiles (
    id,
    display_name,
    avatar_url
  )
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data ->> 'full_name',
      new.raw_user_meta_data ->> 'name'
    ),
    new.raw_user_meta_data ->> 'avatar_url'
  );

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.join_household_with_code (
  p_code_digest text
)
  RETURNS jsonb
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
declare
  v_user_id uuid := auth.uid();
  v_existing_household_id uuid;
  v_existing_household_name text;
  v_existing_role text;
  v_locked_until timestamptz;
  v_household_id uuid;
  v_household_name text;
  v_membership jsonb;
begin
  if v_user_id is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;

  perform 1
  from public.profiles
  where id = v_user_id
  for update;

  if not found then
    raise exception 'profile not found' using errcode = '23503';
  end if;

  select hm.household_id, h.name, hm.role
  into v_existing_household_id, v_existing_household_name, v_existing_role
  from public.household_members hm
  join public.households h on h.id = hm.household_id
  where hm.user_id = v_user_id;

  if found then
    return jsonb_build_object(
      'status', 'ALREADY_MEMBER',
      'household', jsonb_build_object(
        'id', v_existing_household_id,
        'name', v_existing_household_name
      ),
      'membership', jsonb_build_object(
        'household_id', v_existing_household_id,
        'user_id', v_user_id,
        'role', v_existing_role
      )
    );
  end if;

  v_locked_until := private.household_join_rate_limit(v_user_id, null);
  if v_locked_until is not null then
    return jsonb_build_object(
      'status', 'RATE_LIMITED',
      'retry_after_seconds', greatest(
        1,
        ceil(extract(epoch from (v_locked_until - now())))::integer
      )
    );
  end if;

  if p_code_digest ~ '^[0-9a-f]{64}$' then
    select c.household_id, h.name
    into v_household_id, v_household_name
    from public.household_join_codes c
    join public.households h on h.id = c.household_id
    where c.code_digest = p_code_digest
      and c.expires_at > now()
    for update of c;
  end if;

  if v_household_id is null then
    perform private.household_join_rate_limit(v_user_id, false);
    return jsonb_build_object('status', 'INVALID_OR_EXPIRED');
  end if;

  insert into public.household_members (household_id, user_id, role)
  values (v_household_id, v_user_id, 'member')
  returning jsonb_build_object(
    'id', id,
    'household_id', household_id,
    'user_id', user_id,
    'role', role,
    'joined_at', joined_at
  ) into v_membership;

  update public.profiles
  set onboarding_completed_at = now(),
      updated_at = now()
  where id = v_user_id;

  if not found then
    raise exception 'profile not found' using errcode = '23503';
  end if;

  delete from public.household_join_codes
  where household_id = v_household_id
    and code_digest = p_code_digest;

  if not found then
    raise exception 'join code disappeared during redemption';
  end if;

  perform private.household_join_rate_limit(v_user_id, true);

  return jsonb_build_object(
    'status', 'JOINED',
    'household', jsonb_build_object(
      'id', v_household_id,
      'name', v_household_name
    ),
    'membership', v_membership
  );
end;
$function$;

CREATE OR REPLACE FUNCTION public.leave_household()
  RETURNS jsonb
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
declare
  v_user_id uuid := auth.uid();
  v_household_id uuid;
  v_role text;
begin
  if v_user_id is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;

  perform 1
  from public.profiles
  where id = v_user_id
  for update;

  if not found then
    raise exception 'profile not found' using errcode = '23503';
  end if;

  select household_id, role
  into v_household_id, v_role
  from public.household_members
  where user_id = v_user_id
  for update;

  if not found then
    return jsonb_build_object('status', 'NO_HOUSEHOLD');
  end if;

  if v_role = 'owner' then
    return jsonb_build_object('status', 'OWNER_CANNOT_LEAVE');
  end if;

  delete from public.household_recipe_shares shares
  using public.recipes recipes
  where shares.household_id = v_household_id
    and shares.recipe_id = recipes.id
    and recipes.owner_user_id = v_user_id;

  delete from public.household_members
  where household_id = v_household_id
    and user_id = v_user_id;

  if not found then
    raise exception 'household membership disappeared while leaving';
  end if;

  update public.profiles
  set onboarding_completed_at = null,
      updated_at = now()
  where id = v_user_id;

  if not found then
    raise exception 'profile not found' using errcode = '23503';
  end if;

  return jsonb_build_object('status', 'LEFT');
end;
$function$;

CREATE OR REPLACE FUNCTION public.mark_household_activity_read (
  p_through_activity_id bigint
)
  RETURNS jsonb
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
declare
  v_user_id uuid := auth.uid();
  v_household_id uuid;
  v_joined_at timestamptz;
begin
  if v_user_id is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;

  select members.household_id, members.joined_at
  into v_household_id, v_joined_at
  from public.household_members members
  where members.user_id = v_user_id
  for update;

  if not found then
    return jsonb_build_object('status', 'NO_HOUSEHOLD');
  end if;

  if p_through_activity_id is null or not exists (
    select 1
    from public.household_recipe_activities activities
    where activities.id = p_through_activity_id
      and activities.household_id = v_household_id
      and activities.created_at >= v_joined_at
  ) then
    return jsonb_build_object('status', 'INVALID_ACTIVITY');
  end if;

  update public.household_members members
  set last_seen_activity_id = greatest(
    coalesce(members.last_seen_activity_id, 0),
    p_through_activity_id
  )
  where members.user_id = v_user_id;

  return jsonb_build_object('status', 'OK');
end;
$function$;

CREATE OR REPLACE FUNCTION public.preview_household_join_code (
  p_code_digest text
)
  RETURNS jsonb
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
declare
  v_user_id uuid := auth.uid();
  v_existing_household_id uuid;
  v_existing_role text;
  v_locked_until timestamptz;
  v_household_id uuid;
  v_household_name text;
  v_owner_display_name text;
  v_member_count integer;
begin
  if v_user_id is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;

  select household_id, role
  into v_existing_household_id, v_existing_role
  from public.household_members
  where user_id = v_user_id;

  if found then
    return jsonb_build_object(
      'status', 'ALREADY_MEMBER',
      'household_id', v_existing_household_id,
      'role', v_existing_role
    );
  end if;

  v_locked_until := private.household_join_rate_limit(v_user_id, null);
  if v_locked_until is not null then
    return jsonb_build_object(
      'status', 'RATE_LIMITED',
      'retry_after_seconds', greatest(
        1,
        ceil(extract(epoch from (v_locked_until - now())))::integer
      )
    );
  end if;

  if p_code_digest ~ '^[0-9a-f]{64}$' then
    select
      h.id,
      h.name,
      coalesce(
        nullif(to_jsonb(p) ->> 'display_name', ''),
        nullif(to_jsonb(p) ->> 'full_name', ''),
        nullif(to_jsonb(p) ->> 'name', ''),
        'Household owner'
      ),
      (
        select count(*)::integer
        from public.household_members members
        where members.household_id = h.id
      )
    into
      v_household_id,
      v_household_name,
      v_owner_display_name,
      v_member_count
    from public.household_join_codes c
    join public.households h on h.id = c.household_id
    left join public.profiles p on p.id = h.created_by
    where c.code_digest = p_code_digest
      and c.expires_at > now();
  end if;

  if v_household_id is null then
    perform private.household_join_rate_limit(v_user_id, false);
    return jsonb_build_object('status', 'INVALID_OR_EXPIRED');
  end if;

  perform private.household_join_rate_limit(v_user_id, true);

  return jsonb_build_object(
    'status', 'OK',
    'household_name', v_household_name,
    'owner_display_name', v_owner_display_name,
    'member_count', v_member_count
  );
end;
$function$;

CREATE OR REPLACE FUNCTION public.replace_household_join_code (
  p_code_digest text
)
  RETURNS jsonb
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
declare
  v_user_id uuid := auth.uid();
  v_household_id uuid;
  v_expires_at timestamptz := now() + interval '10 minutes';
begin
  if v_user_id is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;

  if p_code_digest !~ '^[0-9a-f]{64}$' then
    raise exception 'invalid code digest' using errcode = '22023';
  end if;

  select household_id
  into v_household_id
  from public.household_members
  where user_id = v_user_id
    and role = 'owner';

  if not found then
    return jsonb_build_object('status', 'FORBIDDEN');
  end if;

  insert into public.household_join_codes (
    household_id,
    code_digest,
    created_by,
    created_at,
    expires_at
  ) values (
    v_household_id,
    p_code_digest,
    v_user_id,
    now(),
    v_expires_at
  )
  on conflict (household_id) do update
  set code_digest = excluded.code_digest,
      created_by = excluded.created_by,
      created_at = excluded.created_at,
      expires_at = excluded.expires_at;

  return jsonb_build_object(
    'status', 'OK',
    'expires_at', v_expires_at
  );
end;
$function$;

CREATE OR REPLACE FUNCTION public.replace_personal_cookbook_recipes (
  p_cookbook_id uuid,
  p_recipe_ids  uuid[] DEFAULT '{}'::uuid[]
)
  RETURNS jsonb
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;

  perform 1
  from public.cookbooks cookbooks
  where cookbooks.id = p_cookbook_id
    and cookbooks.owner_user_id = v_user_id
  for update;

  if not found then
    return jsonb_build_object('status', 'COOKBOOK_NOT_FOUND');
  end if;

  if exists (
    select 1
    from unnest(coalesce(p_recipe_ids, '{}'::uuid[])) selected(recipe_id)
    where selected.recipe_id is null
      or not exists (
        select 1
        from public.recipes recipes
        where recipes.id = selected.recipe_id
          and recipes.owner_user_id = v_user_id
      )
  ) then
    return jsonb_build_object('status', 'INVALID_RECIPE');
  end if;

  delete from public.cookbook_recipes cookbook_recipes
  where cookbook_recipes.cookbook_id = p_cookbook_id;

  insert into public.cookbook_recipes (cookbook_id, recipe_id)
  select p_cookbook_id, selected.recipe_id
  from (
    select distinct recipe_id
    from unnest(coalesce(p_recipe_ids, '{}'::uuid[])) recipe_ids(recipe_id)
  ) selected;

  return jsonb_build_object('status', 'OK');
end;
$function$;

CREATE OR REPLACE FUNCTION public.revoke_household_join_code()
  RETURNS jsonb
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
declare
  v_user_id uuid := auth.uid();
  v_household_id uuid;
  v_deleted_count integer;
begin
  if v_user_id is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;

  select household_id
  into v_household_id
  from public.household_members
  where user_id = v_user_id
    and role = 'owner';

  if not found then
    return jsonb_build_object('status', 'FORBIDDEN');
  end if;

  delete from public.household_join_codes
  where household_id = v_household_id;

  get diagnostics v_deleted_count = row_count;

  return jsonb_build_object(
    'status', 'OK',
    'deleted', v_deleted_count > 0
  );
end;
$function$;

CREATE OR REPLACE FUNCTION public.set_recipe_household_shared (
  p_recipe_id uuid,
  p_shared    boolean
)
  RETURNS jsonb
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
declare
  v_user_id uuid := auth.uid();
  v_household_id uuid;
  v_changed_household_id uuid;
  v_member_count integer;
  v_recipe_title text;
begin
  if v_user_id is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;

  if p_shared is null then
    raise exception 'shared state is required' using errcode = '22023';
  end if;

  select members.household_id
  into v_household_id
  from public.household_members members
  where members.user_id = v_user_id;

  if not found then
    return jsonb_build_object('status', 'NO_HOUSEHOLD');
  end if;

  select recipes.title
  into v_recipe_title
  from public.recipes recipes
  where recipes.id = p_recipe_id
    and recipes.owner_user_id = v_user_id;

  if not found then
    return jsonb_build_object('status', 'RECIPE_NOT_FOUND');
  end if;

  if p_shared then
    select count(*)::integer
    into v_member_count
    from public.household_members members
    where members.household_id = v_household_id;

    if v_member_count < 2 then
      return jsonb_build_object('status', 'HOUSEHOLD_NOT_READY');
    end if;

    insert into public.household_recipe_shares (household_id, recipe_id)
    values (v_household_id, p_recipe_id)
    on conflict (household_id, recipe_id) do nothing
    returning household_id into v_changed_household_id;

    if v_changed_household_id is not null then
      perform private.record_household_recipe_activity(
        v_household_id,
        p_recipe_id,
        v_recipe_title,
        'added'
      );
    end if;
  else
    delete from public.household_recipe_shares shares
    where shares.household_id = v_household_id
      and shares.recipe_id = p_recipe_id
    returning household_id into v_changed_household_id;

    if v_changed_household_id is not null then
      perform private.record_household_recipe_activity(
        v_household_id,
        p_recipe_id,
        v_recipe_title,
        'unshared'
      );
    end if;
  end if;

  return jsonb_build_object('status', 'OK', 'is_shared', p_shared);
end;
$function$;

ALTER TABLE "public"."cookbook_recipes"
  ADD CONSTRAINT "cookbook_recipes_cookbook_id_fkey" FOREIGN KEY (cookbook_id) REFERENCES public.cookbooks(id) ON DELETE CASCADE;

ALTER TABLE "public"."household_members"
  ADD CONSTRAINT "household_members_last_seen_activity_id_fkey" FOREIGN KEY (last_seen_activity_id) REFERENCES public.household_recipe_activities(id) ON DELETE SET NULL;

ALTER TABLE "public"."household_join_codes"
  ADD CONSTRAINT "household_join_codes_household_id_fkey" FOREIGN KEY (household_id) REFERENCES public.households(id) ON DELETE CASCADE;

ALTER TABLE "public"."household_members"
  ADD CONSTRAINT "household_members_household_id_fkey" FOREIGN KEY (household_id) REFERENCES public.households(id) ON DELETE CASCADE;

ALTER TABLE "public"."household_recipe_activities"
  ADD CONSTRAINT "household_recipe_activities_household_id_fkey" FOREIGN KEY (household_id) REFERENCES public.households(id) ON DELETE CASCADE;

ALTER TABLE "public"."household_recipe_shares"
  ADD CONSTRAINT "household_recipe_shares_household_id_fkey" FOREIGN KEY (household_id) REFERENCES public.households(id) ON DELETE CASCADE;

ALTER TABLE "public"."profiles"
  ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."cookbooks"
  ADD CONSTRAINT "cookbooks_owner_user_id_fkey" FOREIGN KEY (owner_user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

ALTER TABLE "public"."household_join_codes"
  ADD CONSTRAINT "household_join_codes_created_by_fkey" FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE CASCADE;

ALTER TABLE "public"."household_join_rate_limits"
  ADD CONSTRAINT "household_join_rate_limits_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

ALTER TABLE "public"."household_members"
  ADD CONSTRAINT "household_members_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

ALTER TABLE "public"."household_recipe_activities"
  ADD CONSTRAINT "household_recipe_activities_actor_user_id_fkey" FOREIGN KEY (actor_user_id) REFERENCES public.profiles(id) ON DELETE SET NULL;

ALTER TABLE "public"."households"
  ADD CONSTRAINT "households_created_by_fkey" FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE SET NULL;

ALTER TABLE "public"."recipes"
  ADD CONSTRAINT "recipes_owner_user_id_fkey" FOREIGN KEY (owner_user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

ALTER TABLE "public"."cookbook_recipes"
  ADD CONSTRAINT "cookbook_recipes_recipe_id_fkey" FOREIGN KEY (recipe_id) REFERENCES public.recipes(id) ON DELETE CASCADE;

ALTER TABLE "public"."household_recipe_activities"
  ADD CONSTRAINT "household_recipe_activities_recipe_id_fkey" FOREIGN KEY (recipe_id) REFERENCES public.recipes(id) ON DELETE SET NULL;

ALTER TABLE "public"."household_recipe_shares"
  ADD CONSTRAINT "household_recipe_shares_recipe_id_fkey" FOREIGN KEY (recipe_id) REFERENCES public.recipes(id) ON DELETE CASCADE;

CREATE INDEX cookbook_recipes_recipe_idx ON public.cookbook_recipes USING btree (recipe_id);

CREATE INDEX cookbooks_owner_created_idx ON public.cookbooks USING btree (owner_user_id, created_at DESC);

CREATE UNIQUE INDEX household_members_one_household_per_user ON public.household_members USING btree (user_id);

CREATE UNIQUE INDEX household_members_one_owner_per_household ON public.household_members USING btree (household_id)
  WHERE (ROLE = 'owner'::text);

CREATE INDEX household_recipe_activities_household_id_id_idx ON public.household_recipe_activities USING btree (household_id, id DESC);

CREATE INDEX idx_recipes_owner_created_at ON public.recipes USING btree (owner_user_id, created_at DESC);

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

CREATE TRIGGER record_shared_recipe_edit
  AFTER UPDATE OF title,
    description, ingredients, instructions, servings, prep_time_minutes, cook_time_minutes, nutrition_per_serving, source_type, source_person_name, source_url ON public.recipes
  FOR EACH ROW
  EXECUTE FUNCTION private.record_shared_recipe_edit();

CREATE POLICY "users can read personal cookbook recipes" ON "public"."cookbook_recipes"
  FOR SELECT
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.cookbooks cookbooks
  WHERE ((cookbooks.id = cookbook_recipes.cookbook_id) AND (cookbooks.owner_user_id = ( SELECT auth.uid() AS uid))))));

CREATE POLICY "users can create personal cookbooks" ON "public"."cookbooks"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((owner_user_id = ( SELECT auth.uid() AS uid)));

CREATE POLICY "users can delete personal cookbooks" ON "public"."cookbooks"
  FOR DELETE
  TO "authenticated"
  USING ((owner_user_id = ( SELECT auth.uid() AS uid)));

CREATE POLICY "users can read personal cookbooks" ON "public"."cookbooks"
  FOR SELECT
  TO "authenticated"
  USING ((owner_user_id = ( SELECT auth.uid() AS uid)));

CREATE POLICY "users can rename personal cookbooks" ON "public"."cookbooks"
  FOR UPDATE
  TO "authenticated"
  USING ((owner_user_id = ( SELECT auth.uid() AS uid)))
  WITH CHECK ((owner_user_id = ( SELECT auth.uid() AS uid)));

CREATE POLICY "Users can add themselves as owner of own household" ON "public"."household_members"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (((( SELECT auth.uid() AS uid) = user_id) AND (role = 'owner'::text) AND (EXISTS ( SELECT 1
   FROM public.households h
  WHERE ((h.id = household_members.household_id) AND (h.created_by = ( SELECT auth.uid() AS uid)))))));

CREATE POLICY "Users can view own membership" ON "public"."household_members"
  FOR SELECT
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = user_id));

CREATE POLICY "household members can read recipe shares" ON "public"."household_recipe_shares"
  FOR SELECT
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.household_members members
  WHERE ((members.household_id = household_recipe_shares.household_id) AND (members.user_id = ( SELECT auth.uid() AS uid))))));

CREATE POLICY "Users can create own household" ON "public"."households"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((( SELECT auth.uid() AS uid) = created_by));

CREATE POLICY "Users can view own household" ON "public"."households"
  FOR SELECT
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = created_by));

CREATE POLICY "Users can read own profile" ON "public"."profiles"
  FOR SELECT
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = id));

CREATE POLICY "Users can update own profile" ON "public"."profiles"
  FOR UPDATE
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = id))
  WITH CHECK ((( SELECT auth.uid() AS uid) = id));

CREATE POLICY "household members can read shared recipes" ON "public"."recipes"
  FOR SELECT
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM (public.household_recipe_shares shares
     JOIN public.household_members members ON ((members.household_id = shares.household_id)))
  WHERE ((shares.recipe_id = recipes.id) AND (members.user_id = ( SELECT auth.uid() AS uid))))));

CREATE POLICY "recipe owners can create" ON "public"."recipes"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((( SELECT auth.uid() AS uid) = owner_user_id));

CREATE POLICY "recipe owners can delete recipes" ON "public"."recipes"
  FOR DELETE
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = owner_user_id));

CREATE POLICY "recipe owners can read" ON "public"."recipes"
  FOR SELECT
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = owner_user_id));

CREATE POLICY "recipe owners can update" ON "public"."recipes"
  FOR UPDATE
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = owner_user_id))
  WITH CHECK ((( SELECT auth.uid() AS uid) = owner_user_id));

REVOKE ALL ON FUNCTION "private"."household_join_rate_limit"(uuid, boolean) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "private"."household_join_rate_limit"(uuid, boolean) TO "postgres";

REVOKE ALL ON FUNCTION "private"."record_household_recipe_activity"(uuid, uuid, text, text) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "private"."record_household_recipe_activity"(uuid, uuid, text, text) TO "postgres";

REVOKE ALL ON FUNCTION "private"."record_shared_recipe_edit"() FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "private"."record_shared_recipe_edit"() TO "postgres";

REVOKE ALL ON FUNCTION "public"."create_personal_cookbook"(text, uuid[]) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."create_personal_cookbook"(text, uuid[]) TO "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."get_household_activity"() FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."get_household_activity"() TO "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."get_household_settings"() FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."get_household_settings"() TO "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."handle_new_user"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."join_household_with_code"(text) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."join_household_with_code"(text) TO "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."leave_household"() FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."leave_household"() TO "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."mark_household_activity_read"(bigint) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."mark_household_activity_read"(bigint) TO "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."preview_household_join_code"(text) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."preview_household_join_code"(text) TO "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."replace_household_join_code"(text) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."replace_household_join_code"(text) TO "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."replace_personal_cookbook_recipes"(uuid, uuid[]) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."replace_personal_cookbook_recipes"(uuid, uuid[]) TO "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."revoke_household_join_code"() FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."revoke_household_join_code"() TO "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."set_recipe_household_shared"(uuid, boolean) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."set_recipe_household_shared"(uuid, boolean) TO "authenticated", "postgres", "service_role";

GRANT CREATE, USAGE ON SCHEMA "private" TO "postgres";

REVOKE ALL ON TABLE "public"."cookbook_recipes" FROM "anon";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."cookbook_recipes" TO "anon";

REVOKE ALL ON TABLE "public"."cookbook_recipes" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."cookbook_recipes" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."cookbook_recipes" TO "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."cookbooks" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."household_join_codes" TO "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."household_join_rate_limits" TO "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."household_members" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."household_recipe_activities" TO "postgres", "service_role";

REVOKE ALL ON TABLE "public"."household_recipe_shares" FROM "anon";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."household_recipe_shares" TO "anon";

REVOKE ALL ON TABLE "public"."household_recipe_shares" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."household_recipe_shares" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."household_recipe_shares" TO "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."households" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."profiles" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."recipes" TO "anon", "authenticated", "postgres", "service_role";
